# Generated by Django 2.2 on 2019-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_book_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
