# Generated by Django 2.2.1 on 2020-02-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='libranian',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='student',
        ),
        migrations.RemoveField(
            model_name='libranian',
            name='user',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.RemoveField(
            model_name='return',
            name='book',
        ),
        migrations.RemoveField(
            model_name='return',
            name='libranian',
        ),
        migrations.RemoveField(
            model_name='return',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Libranian',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
