# Generated by Django 2.2.1 on 2020-03-29 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_auto_20200229_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
