# Generated by Django 3.0.3 on 2020-04-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_auto_20200329_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Book'),
        ),
    ]
